version: '3.1'

services:

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d

  api:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env

  # postgres:
  #   image: postgres
  #   restart: unless-stopped
  #   env_file:
  #     - .env
